blueprint:
  name: Awtrix 3 app to show sensor value
  description: >
    Creates an Awtrix 3 application via an MQTT message.
    Particularly useful for displaying sensor values from a Netatmo weather station
    or a solar system
  domain: automation
  input:
    sensor:
      name: Sensor
      description: This sensor will be shown on awtrix 3.
      selector:
        entity:
          domain:
            - sensor
          multiple: false
    threshold_no_show:
      name: threshold no show
      description: If sensor value is below this value do not show this custom app on awtrix 3.
      selector:
        number:
          mode: box
    threshold_warn:
      name: threshold warn
      description: If sensor value is above this value show the value in red.
      selector:
        number:
          mode: box
    decimal_places:
      name: decimal places
      description: How many decimal places of the sensor value do you want to display?
      default: 0
      selector:
        number:
          mode: box
    mqqt_topic:
      name: mqtt topic
      default: awtrix-light-1/custom/my-app-name
    icon_id:
      name: icon id
    position:
      name: position
      description: At which postion shall the custom app be shown
      default: 1
      selector:
        number:
          mode: box
variables:
  sensor: !input sensor
  icon_id: !input icon_id
  threshold_no_show: !input threshold_no_show
  threshold_warn: !input threshold_warn
  decimal_places: !input decimal_places
  position: !input position
trigger:
  - platform: state
    entity_id:
      - !input sensor
  - platform: time_pattern
    hours: "*"
  - platform: time
    at: "06:30:04"
condition: []
action:
  - service: mqtt.publish
    data:
      topic: !input mqqt_topic
      payload: >-
        {% set value = float(states(sensor, rounded=false)) %}
        {% set unit = state_attr(sensor, 'unit_of_measurement') %}
        {% set baseNotification = { "icon": icon_id, "text":
         value | round(decimal_places) | string + ' ' + unit,
        "pos": position
        }  %}
        {% set warnNotification = {
         "color" : "#FF0000"
        }  %}
        {% if value <= threshold_no_show -%} {}
        {% elif value <= threshold_warn -%} {{baseNotification | to_json }}
        {%- else -%} {{dict(baseNotification, **warnNotification) | to_json }}
        {%- endif %}
mode: single
